### ISSUE TITLE
Proper unit testing

### ISSUE THREAD

**Issue by nvgrw** [flintrocks/flint#48]
The compiler is steadily growing in complexity and scale.

It is about time that we add at least a degree of unit testing.

# TODO
- [ ] Decide which testing framework to use. Does XCTest work on Linux?
- [ ] Prioritise which units to test first. Go for low hanging fruit (no/little refactoring required, small).
- [ ] Strategise about which units can be refactored and how the compiler design may need to change.

**Comment by nvgrw** [comment]
Currently evaluating whether to use [Cuckoo](https://github.com/Brightify/Cuckoo) for boilerplate-free mocking akin to JMock. Some code generation is required as Swift does not have reflection.
